### ISSUE TITLE
Sprint 1 Walkthrough

### ISSUE THREAD

**Issue by iriswang** [kevrain/Consens.us#1]
We changed the app idea from a food truck finder to an event planning app. The main idea is that our app allows groups of users to generate polls to decide where/ when they want to plan their event.

The user stories we've implemented are:
- Group creation (Pulls up all your facebook friends who also utilize the app)
- View all groups
- Poll creation (with many candidate location/ date associated with each poll)
- View all polls associated with one group
- View poll details

Here is a gif walkthrough of what we have so far:
![sprint1walkthrough](https://cloud.githubusercontent.com/assets/2382491/17871518/bcbe8c6e-6870-11e6-8c18-efba956e699b.gif)

@codepathreview @codepath

**Comment by codepathreview** [comment]
:+1: Nice work creating tasks for sprint 1. The goal of this sprint is to have the basic screens and workflows ready as much as possible. A few notes
- Consider creating a project wiki so you can have a thorough documentation of all design decisions made during the project. You have a good start on this by listing down required and advanced features on [README](https://github.com/kevrain/Consens.us/blob/master/README.md).
- Tasks are well defined and seem achievable in the given timeframe
- Good work dividing tasks among team members. This is critical in working as a team and also gives equal learning opportunity to everyone involved
- Good to see everyone [contributing](https://github.com/kevrain/Consens.us/graphs/contributors) to the project.
- Depending on the strategy your group has come up with, consider creating regular pull requests to sync up your code to avoid having multiple merge conflicts at the end.
- Group projects can reinforce skills that are relevant to both group and individual work including the ability to plan and manage time. For this reason, it is imperative that you group all detailed issues into [milestones](https://github.com/kevrain/Consens.us/milestones) representing sprints so that its easier for you to track progress of the project.
- Consider creating tasks to QA the app a few times to check the basic flow. Integration testing will especially be important for this project since each team member is working on a separate module. The best part is seeing it all come together into a polished app.

Consider incorporating as many screens as possible in this sprint so you can have enough time to add UI polish and advanced features later on. It is those little extra things you do that make everything feel more polished and desirable to use. Look forward to what you all come up with.
